*************************************
*************************************
# LET'S PLAY BINGO
*************************************
*************************************  
Author: Probal Mojumder  
Date: 9th April, 2020

## A. Creating the BINGO cards  
  
  ### 1. Whole 5 by 5 cards with 1 to 75 as numbers

In [1]:
import numpy as np

In [2]:
def unique_rand_func(n):
    rand = (np.random.randint(n) + 1)
    if rand not in index:
        return rand
    else:
        rand = unique_rand_func(n)
        return rand

In [3]:
card = np.zeros((5,5))
card

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
index = []
for i in range(5):
    for j in range(5):
            current_rand = unique_rand_func(75)
            card[i][j] = current_rand
            index.append(current_rand)

In [5]:
card

array([[67., 17., 43.,  7., 75.],
       [ 8.,  9.,  5., 57., 35.],
       [72., 54., 22., 23., 37.],
       [13.,  4.,  1., 36., 63.],
       [59., 24., 47., 40., 31.]])

  ### 2. Whole 5 by 5 cards with 1 to 75 as numbers, such that 1st column 1 to 15, 2nd column 16 to 30, so on ..

In [6]:
card = np.zeros((5,5))
card

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
for j in range(5):
    index = []
    for i in range(5):
            current_rand = unique_rand_func(15)
            card[i][j] = current_rand + j*15
            index.append(current_rand)

In [8]:
card

array([[ 5., 26., 33., 55., 61.],
       [ 3., 20., 31., 59., 65.],
       [15., 22., 43., 58., 71.],
       [ 6., 29., 35., 48., 70.],
       [ 1., 28., 39., 52., 63.]])

## B. Playing BINGO   

In [9]:
index = []
count = 0

while count <= 75:
    rand = unique_rand_func(75)
    index.append(rand)
    
    # Is the number in card?
    for i in range(5):
        for j in range(5):
            if card[i][j] == rand:
                card[i][j] = 0
    
    # Check for a BINGO!
    card_hsum = np.sum(card, axis=1)
    card_vsum = np.sum(card, axis=0) 
    card_diag = card.diagonal().sum()
    card_flip_diag = np.fliplr(card).diagonal().sum()
    card_center_and_corners = card[0][0] + card[0][4] + card[4][0] + card[4][4] + card[2][2]
    
    if (0 in card_hsum) or (0 in card_vsum) or 0==card_diag or 0==card_flip_diag or 0==card_center_and_corners:
        print("Bingo!!!")
        print(f"Play round is {count}")
        break
    
    count += 1            

Bingo!!!
Play round is 52


In [10]:
index #The BINGO Calls

[54,
 21,
 13,
 61,
 67,
 27,
 18,
 48,
 42,
 64,
 19,
 5,
 11,
 58,
 62,
 33,
 9,
 45,
 46,
 25,
 59,
 10,
 38,
 43,
 2,
 39,
 41,
 36,
 69,
 14,
 66,
 30,
 72,
 37,
 3,
 23,
 15,
 8,
 28,
 49,
 24,
 32,
 51,
 17,
 60,
 1,
 74,
 35,
 52,
 34,
 73,
 71,
 55]

In [11]:
card #The BINGO Card

array([[ 0., 26.,  0.,  0.,  0.],
       [ 0., 20., 31.,  0., 65.],
       [ 0., 22.,  0.,  0.,  0.],
       [ 6., 29.,  0.,  0., 70.],
       [ 0.,  0.,  0.,  0., 63.]])